services:
  download-server:  # 服务名称
    image: download-server  # 使用的镜像名称
    container_name: download-server  # 容器名称
    ports:
      - "8080:8080"  # 将容器的 8080 端口映射到主机的 8080 端口
    volumes:
      - ./download:/app/downloads  # 挂载宿主机的目录到容器内
    environment:
      - DEFAULT_SAVE_PATH=/app/downloads  # 设置环境变量
      - API_KEY=123456
    restart: always  # 容器意外停止时自动重启